-- Nouveaux produits Hermès (femme + homme), prix fictifs, INACTIFS.
-- Colle ce script dans Supabase -> SQL Editor -> Run.
-- Les fichiers photo attendus sont listes dans hermes-manifeste-photos.md :
-- tant qu'ils ne sont pas dans le depot, les fiches resteront sans image.

begin;

insert into products (id, data) values ('femme-hermes-oran-terres', '{"id": "femme-hermes-oran-terres", "cat": "claquettes", "img": "assets/products/femme/hermes-oran-terres-kaki.jpg", "desc": "Cuir et lézard dans une palette de terre, entre kaki et cognac.", "imgs": ["assets/products/femme/hermes-oran-terres-kaki.jpg", "assets/products/femme/hermes-oran-terres-kaki.jpg", "assets/products/femme/hermes-oran-terres-chocolat-lezard.jpg", "assets/products/femme/hermes-oran-terres-taupe-lezard.jpg", "assets/products/femme/hermes-oran-terres-cognac.jpg"], "name": "Sandale Oran Terres", "badge": "", "price": 52000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "femme", "axes": [{"name": "Pointure", "values": ["36", "37", "38", "39", "40", "41"]}, {"name": "Coloris", "values": ["Kaki", "Chocolat lézard", "Taupe lézard", "Cognac"]}], "variants": {"36::Kaki": {"s": 6, "r": 0}, "36::Chocolat lézard": {"s": 6, "r": 0}, "36::Taupe lézard": {"s": 6, "r": 0}, "36::Cognac": {"s": 6, "r": 0}, "37::Kaki": {"s": 6, "r": 0}, "37::Chocolat lézard": {"s": 6, "r": 0}, "37::Taupe lézard": {"s": 6, "r": 0}, "37::Cognac": {"s": 6, "r": 0}, "38::Kaki": {"s": 6, "r": 0}, "38::Chocolat lézard": {"s": 6, "r": 0}, "38::Taupe lézard": {"s": 6, "r": 0}, "38::Cognac": {"s": 6, "r": 0}, "39::Kaki": {"s": 6, "r": 0}, "39::Chocolat lézard": {"s": 6, "r": 0}, "39::Taupe lézard": {"s": 6, "r": 0}, "39::Cognac": {"s": 6, "r": 0}, "40::Kaki": {"s": 6, "r": 0}, "40::Chocolat lézard": {"s": 6, "r": 0}, "40::Taupe lézard": {"s": 6, "r": 0}, "40::Cognac": {"s": 6, "r": 0}, "41::Kaki": {"s": 6, "r": 0}, "41::Chocolat lézard": {"s": 6, "r": 0}, "41::Taupe lézard": {"s": 6, "r": 0}, "41::Cognac": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Kaki": "assets/products/femme/hermes-oran-terres-kaki.jpg", "Coloris::Chocolat lézard": "assets/products/femme/hermes-oran-terres-chocolat-lezard.jpg", "Coloris::Taupe lézard": "assets/products/femme/hermes-oran-terres-taupe-lezard.jpg", "Coloris::Cognac": "assets/products/femme/hermes-oran-terres-cognac.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('femme-hermes-oran-eclats', '{"id": "femme-hermes-oran-eclats", "cat": "claquettes", "img": "assets/products/femme/hermes-oran-eclats-corail.jpg", "desc": "Cuir lisse et autruche dans des teintes vives, corail et fuchsia.", "imgs": ["assets/products/femme/hermes-oran-eclats-corail.jpg", "assets/products/femme/hermes-oran-eclats-corail.jpg", "assets/products/femme/hermes-oran-eclats-fuchsia-autruche.jpg", "assets/products/femme/hermes-oran-eclats-terracotta-autruche.jpg", "assets/products/femme/hermes-oran-eclats-vert.jpg"], "name": "Sandale Oran Éclats", "badge": "", "price": 54000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "femme", "axes": [{"name": "Pointure", "values": ["36", "37", "38", "39", "40", "41"]}, {"name": "Coloris", "values": ["Corail", "Fuchsia autruche", "Terracotta autruche", "Vert"]}], "variants": {"36::Corail": {"s": 6, "r": 0}, "36::Fuchsia autruche": {"s": 6, "r": 0}, "36::Terracotta autruche": {"s": 6, "r": 0}, "36::Vert": {"s": 6, "r": 0}, "37::Corail": {"s": 6, "r": 0}, "37::Fuchsia autruche": {"s": 6, "r": 0}, "37::Terracotta autruche": {"s": 6, "r": 0}, "37::Vert": {"s": 6, "r": 0}, "38::Corail": {"s": 6, "r": 0}, "38::Fuchsia autruche": {"s": 6, "r": 0}, "38::Terracotta autruche": {"s": 6, "r": 0}, "38::Vert": {"s": 6, "r": 0}, "39::Corail": {"s": 6, "r": 0}, "39::Fuchsia autruche": {"s": 6, "r": 0}, "39::Terracotta autruche": {"s": 6, "r": 0}, "39::Vert": {"s": 6, "r": 0}, "40::Corail": {"s": 6, "r": 0}, "40::Fuchsia autruche": {"s": 6, "r": 0}, "40::Terracotta autruche": {"s": 6, "r": 0}, "40::Vert": {"s": 6, "r": 0}, "41::Corail": {"s": 6, "r": 0}, "41::Fuchsia autruche": {"s": 6, "r": 0}, "41::Terracotta autruche": {"s": 6, "r": 0}, "41::Vert": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Corail": "assets/products/femme/hermes-oran-eclats-corail.jpg", "Coloris::Fuchsia autruche": "assets/products/femme/hermes-oran-eclats-fuchsia-autruche.jpg", "Coloris::Terracotta autruche": "assets/products/femme/hermes-oran-eclats-terracotta-autruche.jpg", "Coloris::Vert": "assets/products/femme/hermes-oran-eclats-vert.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('femme-hermes-oran-pastel-metal', '{"id": "femme-hermes-oran-pastel-metal", "cat": "claquettes", "img": "assets/products/femme/hermes-oran-pastel-menthe-lezard.jpg", "desc": "Lézard pastel et cuir métallisé, pour une paire plus habillée.", "imgs": ["assets/products/femme/hermes-oran-pastel-menthe-lezard.jpg", "assets/products/femme/hermes-oran-pastel-menthe-lezard.jpg", "assets/products/femme/hermes-oran-pastel-sauge-lezard.jpg", "assets/products/femme/hermes-oran-pastel-blanc.jpg", "assets/products/femme/hermes-oran-pastel-argente.jpg"], "name": "Sandale Oran Pastel & Métal", "badge": "", "price": 56000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "femme", "axes": [{"name": "Pointure", "values": ["36", "37", "38", "39", "40", "41"]}, {"name": "Coloris", "values": ["Menthe lézard", "Sauge lézard", "Blanc", "Argenté"]}], "variants": {"36::Menthe lézard": {"s": 6, "r": 0}, "36::Sauge lézard": {"s": 6, "r": 0}, "36::Blanc": {"s": 6, "r": 0}, "36::Argenté": {"s": 6, "r": 0}, "37::Menthe lézard": {"s": 6, "r": 0}, "37::Sauge lézard": {"s": 6, "r": 0}, "37::Blanc": {"s": 6, "r": 0}, "37::Argenté": {"s": 6, "r": 0}, "38::Menthe lézard": {"s": 6, "r": 0}, "38::Sauge lézard": {"s": 6, "r": 0}, "38::Blanc": {"s": 6, "r": 0}, "38::Argenté": {"s": 6, "r": 0}, "39::Menthe lézard": {"s": 6, "r": 0}, "39::Sauge lézard": {"s": 6, "r": 0}, "39::Blanc": {"s": 6, "r": 0}, "39::Argenté": {"s": 6, "r": 0}, "40::Menthe lézard": {"s": 6, "r": 0}, "40::Sauge lézard": {"s": 6, "r": 0}, "40::Blanc": {"s": 6, "r": 0}, "40::Argenté": {"s": 6, "r": 0}, "41::Menthe lézard": {"s": 6, "r": 0}, "41::Sauge lézard": {"s": 6, "r": 0}, "41::Blanc": {"s": 6, "r": 0}, "41::Argenté": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Menthe lézard": "assets/products/femme/hermes-oran-pastel-menthe-lezard.jpg", "Coloris::Sauge lézard": "assets/products/femme/hermes-oran-pastel-sauge-lezard.jpg", "Coloris::Blanc": "assets/products/femme/hermes-oran-pastel-blanc.jpg", "Coloris::Argenté": "assets/products/femme/hermes-oran-pastel-argente.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('femme-hermes-oran-resille', '{"id": "femme-hermes-oran-resille", "cat": "claquettes", "img": "assets/products/femme/hermes-oran-resille-noir.jpg", "desc": "Suédine sur maille ajourée, motif chevrons.", "imgs": ["assets/products/femme/hermes-oran-resille-noir.jpg", "assets/products/femme/hermes-oran-resille-noir.jpg", "assets/products/femme/hermes-oran-resille-rose-poudre.jpg"], "name": "Sandale Oran Résille", "badge": "", "price": 58000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "femme", "axes": [{"name": "Pointure", "values": ["36", "37", "38", "39", "40", "41"]}, {"name": "Coloris", "values": ["Noir", "Rose poudré"]}], "variants": {"36::Noir": {"s": 6, "r": 0}, "36::Rose poudré": {"s": 6, "r": 0}, "37::Noir": {"s": 6, "r": 0}, "37::Rose poudré": {"s": 6, "r": 0}, "38::Noir": {"s": 6, "r": 0}, "38::Rose poudré": {"s": 6, "r": 0}, "39::Noir": {"s": 6, "r": 0}, "39::Rose poudré": {"s": 6, "r": 0}, "40::Noir": {"s": 6, "r": 0}, "40::Rose poudré": {"s": 6, "r": 0}, "41::Noir": {"s": 6, "r": 0}, "41::Rose poudré": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Noir": "assets/products/femme/hermes-oran-resille-noir.jpg", "Coloris::Rose poudré": "assets/products/femme/hermes-oran-resille-rose-poudre.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('femme-hermes-oran-denim', '{"id": "femme-hermes-oran-denim", "cat": "claquettes", "img": "assets/products/femme/hermes-oran-denim-bleu-frange.jpg", "desc": "La découpe Oran en denim, bord frangé ou bordé de cuir.", "imgs": ["assets/products/femme/hermes-oran-denim-bleu-frange.jpg", "assets/products/femme/hermes-oran-denim-bleu-frange.jpg", "assets/products/femme/hermes-oran-denim-tweed-frange.jpg", "assets/products/femme/hermes-oran-denim-bleu-borde.jpg"], "name": "Sandale Oran Denim", "badge": "", "price": 50000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "femme", "axes": [{"name": "Pointure", "values": ["36", "37", "38", "39", "40", "41"]}, {"name": "Coloris", "values": ["Bleu clair frangé", "Tweed frangé", "Bleu clair bordé cuir"]}], "variants": {"36::Bleu clair frangé": {"s": 6, "r": 0}, "36::Tweed frangé": {"s": 6, "r": 0}, "36::Bleu clair bordé cuir": {"s": 6, "r": 0}, "37::Bleu clair frangé": {"s": 6, "r": 0}, "37::Tweed frangé": {"s": 6, "r": 0}, "37::Bleu clair bordé cuir": {"s": 6, "r": 0}, "38::Bleu clair frangé": {"s": 6, "r": 0}, "38::Tweed frangé": {"s": 6, "r": 0}, "38::Bleu clair bordé cuir": {"s": 6, "r": 0}, "39::Bleu clair frangé": {"s": 6, "r": 0}, "39::Tweed frangé": {"s": 6, "r": 0}, "39::Bleu clair bordé cuir": {"s": 6, "r": 0}, "40::Bleu clair frangé": {"s": 6, "r": 0}, "40::Tweed frangé": {"s": 6, "r": 0}, "40::Bleu clair bordé cuir": {"s": 6, "r": 0}, "41::Bleu clair frangé": {"s": 6, "r": 0}, "41::Tweed frangé": {"s": 6, "r": 0}, "41::Bleu clair bordé cuir": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Bleu clair frangé": "assets/products/femme/hermes-oran-denim-bleu-frange.jpg", "Coloris::Tweed frangé": "assets/products/femme/hermes-oran-denim-tweed-frange.jpg", "Coloris::Bleu clair bordé cuir": "assets/products/femme/hermes-oran-denim-bleu-borde.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('femme-hermes-fourrure-croisee', '{"id": "femme-hermes-fourrure-croisee", "cat": "claquettes", "img": "assets/products/femme/hermes-fourrure-camel.jpg", "desc": "Brides croisées en mouton retourné, aucun rapport avec la découpe Oran.", "imgs": ["assets/products/femme/hermes-fourrure-camel.jpg", "assets/products/femme/hermes-fourrure-camel.jpg", "assets/products/femme/hermes-fourrure-gris.jpg"], "name": "Mule Croisée Fourrure", "badge": "", "price": 45000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "femme", "axes": [{"name": "Pointure", "values": ["36", "37", "38", "39", "40", "41"]}, {"name": "Coloris", "values": ["Camel", "Gris"]}], "variants": {"36::Camel": {"s": 6, "r": 0}, "36::Gris": {"s": 6, "r": 0}, "37::Camel": {"s": 6, "r": 0}, "37::Gris": {"s": 6, "r": 0}, "38::Camel": {"s": 6, "r": 0}, "38::Gris": {"s": 6, "r": 0}, "39::Camel": {"s": 6, "r": 0}, "39::Gris": {"s": 6, "r": 0}, "40::Camel": {"s": 6, "r": 0}, "40::Gris": {"s": 6, "r": 0}, "41::Camel": {"s": 6, "r": 0}, "41::Gris": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Camel": "assets/products/femme/hermes-fourrure-camel.jpg", "Coloris::Gris": "assets/products/femme/hermes-fourrure-gris.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('hermes-chypre-daim', '{"id": "hermes-chypre-daim", "cat": "claquettes", "img": "assets/products/homme/hermes-chypre-daim-bleu-ciel.jpg", "desc": "Chypre en veau daim, bride large réglable.", "imgs": ["assets/products/homme/hermes-chypre-daim-bleu-ciel.jpg", "assets/products/homme/hermes-chypre-daim-bleu-ciel.jpg", "assets/products/homme/hermes-chypre-daim-gris-bleu.jpg", "assets/products/homme/hermes-chypre-daim-chocolat.jpg", "assets/products/homme/hermes-chypre-daim-sable.jpg", "assets/products/homme/hermes-chypre-daim-beige-lezard.jpg"], "name": "Sandale Chypre Daim", "badge": "", "price": 53000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "homme", "axes": [{"name": "Pointure", "values": ["39", "40", "41", "42", "43", "44", "45"]}, {"name": "Coloris", "values": ["Bleu ciel", "Gris-bleu", "Chocolat", "Sable", "Beige lézard"]}], "variants": {"39::Bleu ciel": {"s": 6, "r": 0}, "39::Gris-bleu": {"s": 6, "r": 0}, "39::Chocolat": {"s": 6, "r": 0}, "39::Sable": {"s": 6, "r": 0}, "39::Beige lézard": {"s": 6, "r": 0}, "40::Bleu ciel": {"s": 6, "r": 0}, "40::Gris-bleu": {"s": 6, "r": 0}, "40::Chocolat": {"s": 6, "r": 0}, "40::Sable": {"s": 6, "r": 0}, "40::Beige lézard": {"s": 6, "r": 0}, "41::Bleu ciel": {"s": 6, "r": 0}, "41::Gris-bleu": {"s": 6, "r": 0}, "41::Chocolat": {"s": 6, "r": 0}, "41::Sable": {"s": 6, "r": 0}, "41::Beige lézard": {"s": 6, "r": 0}, "42::Bleu ciel": {"s": 6, "r": 0}, "42::Gris-bleu": {"s": 6, "r": 0}, "42::Chocolat": {"s": 6, "r": 0}, "42::Sable": {"s": 6, "r": 0}, "42::Beige lézard": {"s": 6, "r": 0}, "43::Bleu ciel": {"s": 6, "r": 0}, "43::Gris-bleu": {"s": 6, "r": 0}, "43::Chocolat": {"s": 6, "r": 0}, "43::Sable": {"s": 6, "r": 0}, "43::Beige lézard": {"s": 6, "r": 0}, "44::Bleu ciel": {"s": 6, "r": 0}, "44::Gris-bleu": {"s": 6, "r": 0}, "44::Chocolat": {"s": 6, "r": 0}, "44::Sable": {"s": 6, "r": 0}, "44::Beige lézard": {"s": 6, "r": 0}, "45::Bleu ciel": {"s": 6, "r": 0}, "45::Gris-bleu": {"s": 6, "r": 0}, "45::Chocolat": {"s": 6, "r": 0}, "45::Sable": {"s": 6, "r": 0}, "45::Beige lézard": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Bleu ciel": "assets/products/homme/hermes-chypre-daim-bleu-ciel.jpg", "Coloris::Gris-bleu": "assets/products/homme/hermes-chypre-daim-gris-bleu.jpg", "Coloris::Chocolat": "assets/products/homme/hermes-chypre-daim-chocolat.jpg", "Coloris::Sable": "assets/products/homme/hermes-chypre-daim-sable.jpg", "Coloris::Beige lézard": "assets/products/homme/hermes-chypre-daim-beige-lezard.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('hermes-chypre-nature', '{"id": "hermes-chypre-nature", "cat": "claquettes", "img": "assets/products/homme/hermes-chypre-nature-vert-olive.jpg", "desc": "Chypre dans des tons naturels, du vert olive au camel.", "imgs": ["assets/products/homme/hermes-chypre-nature-vert-olive.jpg", "assets/products/homme/hermes-chypre-nature-vert-olive.jpg", "assets/products/homme/hermes-chypre-nature-vert-sapin.jpg", "assets/products/homme/hermes-chypre-nature-kaki-fonce.jpg", "assets/products/homme/hermes-chypre-nature-taupe-clair.jpg", "assets/products/homme/hermes-chypre-nature-camel.jpg"], "name": "Sandale Chypre Nature", "badge": "", "price": 53000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "homme", "axes": [{"name": "Pointure", "values": ["39", "40", "41", "42", "43", "44", "45"]}, {"name": "Coloris", "values": ["Vert olive", "Vert sapin", "Kaki foncé", "Taupe clair", "Camel"]}], "variants": {"39::Vert olive": {"s": 6, "r": 0}, "39::Vert sapin": {"s": 6, "r": 0}, "39::Kaki foncé": {"s": 6, "r": 0}, "39::Taupe clair": {"s": 6, "r": 0}, "39::Camel": {"s": 6, "r": 0}, "40::Vert olive": {"s": 6, "r": 0}, "40::Vert sapin": {"s": 6, "r": 0}, "40::Kaki foncé": {"s": 6, "r": 0}, "40::Taupe clair": {"s": 6, "r": 0}, "40::Camel": {"s": 6, "r": 0}, "41::Vert olive": {"s": 6, "r": 0}, "41::Vert sapin": {"s": 6, "r": 0}, "41::Kaki foncé": {"s": 6, "r": 0}, "41::Taupe clair": {"s": 6, "r": 0}, "41::Camel": {"s": 6, "r": 0}, "42::Vert olive": {"s": 6, "r": 0}, "42::Vert sapin": {"s": 6, "r": 0}, "42::Kaki foncé": {"s": 6, "r": 0}, "42::Taupe clair": {"s": 6, "r": 0}, "42::Camel": {"s": 6, "r": 0}, "43::Vert olive": {"s": 6, "r": 0}, "43::Vert sapin": {"s": 6, "r": 0}, "43::Kaki foncé": {"s": 6, "r": 0}, "43::Taupe clair": {"s": 6, "r": 0}, "43::Camel": {"s": 6, "r": 0}, "44::Vert olive": {"s": 6, "r": 0}, "44::Vert sapin": {"s": 6, "r": 0}, "44::Kaki foncé": {"s": 6, "r": 0}, "44::Taupe clair": {"s": 6, "r": 0}, "44::Camel": {"s": 6, "r": 0}, "45::Vert olive": {"s": 6, "r": 0}, "45::Vert sapin": {"s": 6, "r": 0}, "45::Kaki foncé": {"s": 6, "r": 0}, "45::Taupe clair": {"s": 6, "r": 0}, "45::Camel": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Vert olive": "assets/products/homme/hermes-chypre-nature-vert-olive.jpg", "Coloris::Vert sapin": "assets/products/homme/hermes-chypre-nature-vert-sapin.jpg", "Coloris::Kaki foncé": "assets/products/homme/hermes-chypre-nature-kaki-fonce.jpg", "Coloris::Taupe clair": "assets/products/homme/hermes-chypre-nature-taupe-clair.jpg", "Coloris::Camel": "assets/products/homme/hermes-chypre-nature-camel.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('hermes-chypre-bordeaux', '{"id": "hermes-chypre-bordeaux", "cat": "claquettes", "img": "assets/products/homme/hermes-chypre-bordeaux-bordeaux.jpg", "desc": "Chypre en cuir grainé, du bordeaux au bicolore rose.", "imgs": ["assets/products/homme/hermes-chypre-bordeaux-bordeaux.jpg", "assets/products/homme/hermes-chypre-bordeaux-bordeaux.jpg", "assets/products/homme/hermes-chypre-bordeaux-terracotta.jpg", "assets/products/homme/hermes-chypre-bordeaux-rose-pale.jpg", "assets/products/homme/hermes-chypre-bordeaux-bicolore-rose.jpg"], "name": "Sandale Chypre Bordeaux", "badge": "", "price": 54000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "homme", "axes": [{"name": "Pointure", "values": ["39", "40", "41", "42", "43", "44", "45"]}, {"name": "Coloris", "values": ["Bordeaux", "Terracotta", "Rose pâle grainé", "Bicolore rose"]}], "variants": {"39::Bordeaux": {"s": 6, "r": 0}, "39::Terracotta": {"s": 6, "r": 0}, "39::Rose pâle grainé": {"s": 6, "r": 0}, "39::Bicolore rose": {"s": 6, "r": 0}, "40::Bordeaux": {"s": 6, "r": 0}, "40::Terracotta": {"s": 6, "r": 0}, "40::Rose pâle grainé": {"s": 6, "r": 0}, "40::Bicolore rose": {"s": 6, "r": 0}, "41::Bordeaux": {"s": 6, "r": 0}, "41::Terracotta": {"s": 6, "r": 0}, "41::Rose pâle grainé": {"s": 6, "r": 0}, "41::Bicolore rose": {"s": 6, "r": 0}, "42::Bordeaux": {"s": 6, "r": 0}, "42::Terracotta": {"s": 6, "r": 0}, "42::Rose pâle grainé": {"s": 6, "r": 0}, "42::Bicolore rose": {"s": 6, "r": 0}, "43::Bordeaux": {"s": 6, "r": 0}, "43::Terracotta": {"s": 6, "r": 0}, "43::Rose pâle grainé": {"s": 6, "r": 0}, "43::Bicolore rose": {"s": 6, "r": 0}, "44::Bordeaux": {"s": 6, "r": 0}, "44::Terracotta": {"s": 6, "r": 0}, "44::Rose pâle grainé": {"s": 6, "r": 0}, "44::Bicolore rose": {"s": 6, "r": 0}, "45::Bordeaux": {"s": 6, "r": 0}, "45::Terracotta": {"s": 6, "r": 0}, "45::Rose pâle grainé": {"s": 6, "r": 0}, "45::Bicolore rose": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Bordeaux": "assets/products/homme/hermes-chypre-bordeaux-bordeaux.jpg", "Coloris::Terracotta": "assets/products/homme/hermes-chypre-bordeaux-terracotta.jpg", "Coloris::Rose pâle grainé": "assets/products/homme/hermes-chypre-bordeaux-rose-pale.jpg", "Coloris::Bicolore rose": "assets/products/homme/hermes-chypre-bordeaux-bicolore-rose.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

insert into products (id, data) values ('hermes-chypre-vives', '{"id": "hermes-chypre-vives", "cat": "claquettes", "img": "assets/products/homme/hermes-chypre-vives-rouge-vif.jpg", "desc": "Chypre en teintes affirmées, du rouge au léopard.", "imgs": ["assets/products/homme/hermes-chypre-vives-rouge-vif.jpg", "assets/products/homme/hermes-chypre-vives-rouge-vif.jpg", "assets/products/homme/hermes-chypre-vives-fuchsia.jpg", "assets/products/homme/hermes-chypre-vives-nude-daim.jpg", "assets/products/homme/hermes-chypre-vives-leopard.jpg"], "name": "Sandale Chypre Vives", "badge": "", "price": 55000, "active": false, "archived": false, "oldPrice": 0, "stockout": false, "collection": "hermes", "audience": "homme", "axes": [{"name": "Pointure", "values": ["39", "40", "41", "42", "43", "44", "45"]}, {"name": "Coloris", "values": ["Rouge vif", "Fuchsia", "Nude daim", "Léopard"]}], "variants": {"39::Rouge vif": {"s": 6, "r": 0}, "39::Fuchsia": {"s": 6, "r": 0}, "39::Nude daim": {"s": 6, "r": 0}, "39::Léopard": {"s": 6, "r": 0}, "40::Rouge vif": {"s": 6, "r": 0}, "40::Fuchsia": {"s": 6, "r": 0}, "40::Nude daim": {"s": 6, "r": 0}, "40::Léopard": {"s": 6, "r": 0}, "41::Rouge vif": {"s": 6, "r": 0}, "41::Fuchsia": {"s": 6, "r": 0}, "41::Nude daim": {"s": 6, "r": 0}, "41::Léopard": {"s": 6, "r": 0}, "42::Rouge vif": {"s": 6, "r": 0}, "42::Fuchsia": {"s": 6, "r": 0}, "42::Nude daim": {"s": 6, "r": 0}, "42::Léopard": {"s": 6, "r": 0}, "43::Rouge vif": {"s": 6, "r": 0}, "43::Fuchsia": {"s": 6, "r": 0}, "43::Nude daim": {"s": 6, "r": 0}, "43::Léopard": {"s": 6, "r": 0}, "44::Rouge vif": {"s": 6, "r": 0}, "44::Fuchsia": {"s": 6, "r": 0}, "44::Nude daim": {"s": 6, "r": 0}, "44::Léopard": {"s": 6, "r": 0}, "45::Rouge vif": {"s": 6, "r": 0}, "45::Fuchsia": {"s": 6, "r": 0}, "45::Nude daim": {"s": 6, "r": 0}, "45::Léopard": {"s": 6, "r": 0}}, "valueImages": {"Coloris::Rouge vif": "assets/products/homme/hermes-chypre-vives-rouge-vif.jpg", "Coloris::Fuchsia": "assets/products/homme/hermes-chypre-vives-fuchsia.jpg", "Coloris::Nude daim": "assets/products/homme/hermes-chypre-vives-nude-daim.jpg", "Coloris::Léopard": "assets/products/homme/hermes-chypre-vives-leopard.jpg"}}'::jsonb)
  on conflict (id) do update set data = excluded.data, updated_at = now();

-- Ajout de 3 coloris (Noir, Blanc, Marine) a la Chypre deja en ligne (Orange).
update products set data = jsonb_set(
    jsonb_set(
      jsonb_set(data,
        '{axes,1,values}',
        (data->'axes'->1->'values') || '["Noir", "Blanc", "Marine"]'::jsonb),
      '{variants}',
      data->'variants' || '{"39::Noir": {"s": 6, "r": 0}, "39::Blanc": {"s": 6, "r": 0}, "39::Marine": {"s": 6, "r": 0}, "40::Noir": {"s": 6, "r": 0}, "40::Blanc": {"s": 6, "r": 0}, "40::Marine": {"s": 6, "r": 0}, "41::Noir": {"s": 6, "r": 0}, "41::Blanc": {"s": 6, "r": 0}, "41::Marine": {"s": 6, "r": 0}, "42::Noir": {"s": 6, "r": 0}, "42::Blanc": {"s": 6, "r": 0}, "42::Marine": {"s": 6, "r": 0}, "43::Noir": {"s": 6, "r": 0}, "43::Blanc": {"s": 6, "r": 0}, "43::Marine": {"s": 6, "r": 0}, "44::Noir": {"s": 6, "r": 0}, "44::Blanc": {"s": 6, "r": 0}, "44::Marine": {"s": 6, "r": 0}, "45::Noir": {"s": 6, "r": 0}, "45::Blanc": {"s": 6, "r": 0}, "45::Marine": {"s": 6, "r": 0}}'::jsonb),
    '{valueImages}',
    data->'valueImages' || '{"Coloris::Noir": "assets/products/homme/hermes-chypre-essentiels-noir.jpg", "Coloris::Blanc": "assets/products/homme/hermes-chypre-essentiels-blanc.jpg", "Coloris::Marine": "assets/products/homme/hermes-chypre-essentiels-marine.jpg"}'::jsonb
  )
where id = 'hermes-chypre';

commit;

-- Verification
select id, data->>'name' as nom, jsonb_array_length(data->'axes'->1->'values') as nb_coloris
from products where id like 'femme-hermes%' or id like 'hermes-chypre%' order by id;